name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - TODO-UPDATE  # or your deployment branch

jobs:
  deploy:
    name: Deploy via SSH to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/app  # or wherever your app lives
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF