name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add environment variables to .env
        run: |
          echo AUTH_SECRET=${{ secrets.AUTH_SECRET }} >> .env
          echo AUTH_DISCORD_ID=${{ secrets.AUTH_DISCORD_ID }} >> .env
          echo AUTH_DISCORD_SECRET=${{ secrets.AUTH_DISCORD_SECRET }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo AUTH_TRUST_HOST=true >> .env

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/app  # or wherever your app lives
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF